@rem Automatically generated by Amaranth 0.4.1. Do not edit.
@echo off
if defined AMARANTH_ENV_IceStorm call %AMARANTH_ENV_IceStorm%
if defined AMARANTH_ENV_IceStorm call %AMARANTH_ENV_IceStorm%
if [%YOSYS%] equ [""] set YOSYS=
if [%YOSYS%] equ [] set YOSYS=yosys
if [%NEXTPNR_ICE40%] equ [""] set NEXTPNR_ICE40=
if [%NEXTPNR_ICE40%] equ [] set NEXTPNR_ICE40=nextpnr-ice40
if [%ICEPACK%] equ [""] set ICEPACK=
if [%ICEPACK%] equ [] set ICEPACK=icepack
%YOSYS% -q -l top.rpt top.ys || exit /b
%NEXTPNR_ICE40% --quiet --placer heap --log top.tim --hx8k --package bg121 --json top.json --pcf top.pcf --asc top.asc || exit /b
%ICEPACK% top.asc top.bin || exit /b